# Generated by Django 6.0.3 on 2026-03-28 07:45

from django.db import migrations, models


def seed_groups(apps, schema_editor):
    Group = apps.get_model('groups', 'Group')
    names = [
        'Group 1',
        'Group 2',
        'Group 3',
        'Group 4',
    ]
    for name in names:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(seed_groups, migrations.RunPython.noop),
    ]
