# Generated by Django 6.0.3 on 2026-06-03 06:50

from django.db import migrations

def reassign_and_clean_groups(apps, schema_editor):
    Group = apps.get_model('groups', 'Group')
    User = apps.get_model('users', 'User')
    
    # 1. Ensure Group 1-4 exist
    group_1, _ = Group.objects.get_or_create(name='Group 1')
    group_2, _ = Group.objects.get_or_create(name='Group 2')
    group_3, _ = Group.objects.get_or_create(name='Group 3')
    group_4, _ = Group.objects.get_or_create(name='Group 4')
    
    valid_groups = [group_1, group_2, group_3, group_4]
    
    # 2. Find all users not in Group 1-4 (including those with group=None)
    # We only reassign users that actually have a group assigned to a different name
    users_to_reassign = User.objects.filter(group__isnull=False).exclude(group__name__in=['Group 1', 'Group 2', 'Group 3', 'Group 4'])
    
    for i, user in enumerate(users_to_reassign):
        user.group = valid_groups[i % 4]
        user.save(update_fields=['group'])
        
    # 3. Now delete any group that is not Group 1-4
    Group.objects.exclude(name__in=['Group 1', 'Group 2', 'Group 3', 'Group 4']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_capacity_group_is_active'),
    ]

    operations = [
        migrations.RunPython(reassign_and_clean_groups, migrations.RunPython.noop),
    ]
