# Generated by Django 5.1 on 2026-06-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_questionnaire_assessment_type_responseset_milestone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='is_baseline',
        ),
    ]
