# Generated by Django 5.1 on 2026-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_remove_questionnaire_is_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='scores',
            field=models.JSONField(blank=True, default=dict, help_text='Calculated subscale and total scores on submission'),
        ),
    ]
