# Generated by Django 5.1 on 2026-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_responseset_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='suicide_risk_opt_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responseset',
            name='suicide_risk_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='responseset',
            name='milestone',
            field=models.CharField(blank=True, choices=[('SIGNUP', 'Signup Baseline'), ('7_DAYS', '7 Days Post-Test'), ('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('90_DAYS', '90 Days')], db_index=True, max_length=15, null=True),
        ),
    ]
