# Generated by Django 5.1 on 2026-06-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_responseset_suicide_risk_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='responseset',
            name='idx_rs_suicide_risk_status',
        ),
    ]
