# Generated by Django 5.1 on 2026-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_response_question_order_response_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseset',
            name='milestone',
            field=models.CharField(blank=True, choices=[('SIGNUP', 'Signup Baseline'), ('7_DAYS', '7 Days Post-Test'), ('1_MONTH', '1 Month'), ('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('90_DAYS', '90 Days')], db_index=True, max_length=15, null=True),
        ),
    ]
