# Generated by Django 5.1 on 2026-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_alter_responseset_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='suicide_risk_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING', max_length=15),
        ),
    ]
