# Generated by Django 5.1 on 2026-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_remove_utc_truncdate_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='entry_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='entry_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='entry_3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
