# Generated by Django 5.1 on 2026-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_submission_activity_wave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='activity_wave',
            field=models.CharField(choices=[('PRE_T1', 'Pre T1'), ('PRE_T_1M', 'Pre T 1M'), ('PRE_T2', 'Pre T2'), ('PRE_T3', 'Pre T3'), ('PRE_T4', 'Pre T4')], db_index=True, default='PRE_T1', max_length=10),
        ),
    ]
