# Generated by Django 5.1 on 2026-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_sociodemographic',
            field=models.BooleanField(default=False),
        ),
    ]
