# Generated by Django 5.1 on 2026-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_has_completed_sociodemographic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disqualification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
