# Generated by Django 5.1 on 2026-06-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_disqualification_reason_user_is_disqualified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='baseline_completed_at',
            new_name='onboarding_completed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_completed_baseline',
        ),
    ]
